export const GET_CHOCOLATES = "GET_CHOCOLATES";
export const GET_CHOCOLATES_SUCCESS = "GET_CHOCOLATES_SUCCESS";
export const GET_CHOCOLATES_FAILURE = "GET_CHOCOLATES_FAILURE"; 

//chocolates details
// export const GET_CHOCOLATES_DETAILS = "GET_CHOCOLATES_DETAILS";
// export const GET_CHOCOLATES_DETAILS_SUCCESS = "GET_CHOCOLATES_DETAILS_SUCCESS";
// export const GET_CHOCOLATES_DETAILS_FAILURE = "GET_CHOCOLATES_DETAILS_FAILURE";

//brands
export const GET_BRANDS = "GET_BRANDS";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const GET_BRANDS_FAILURE = "GET_BRANDS_FAILURE"; 

//brand details
export const GET_BRANDS_DETAILS = "GET_BRANDS_DETAILS";
export const GET_BRANDS_DETAILS_SUCCESS = "GET_BRANDS_DETAILS_SUCCESS";
export const GET_BRANDS_DETAILS_FAILURE = "GET_BRANDS_DETAILS_FAILURE";

//Login page
export const GET_LOGIN = "GET_LOGIN";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_FAILURE = "GET_LOGIN_FAILURE";

//sign up
export const GET_SIGNUP ="GET_SIGNUP";
export const GET_SIGNUP_SUCCESS ="GET_SIGNUP_SUCCESS";
export const GET_SIGNUP_FAILURE = "GET_SIGNUP_FAILURE";

export const CHANGE_INPUT = "CHANGE_INPUT";

//search
export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";